# references:
# https://trstringer.com/github-actions-multiline-strings/
# https://trstringer.com/github-actions-create-release-upload-artifacts/
# https://github.com/Speedy37/sws/blob/444c67157a98652c4e7ffd3b6d6bbfb664071926/.github/workflows/msbuild.yml
# https://stackoverflow.com/questions/58886293/getting-current-branch-and-commit-hash-in-github-action

name: Build

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Commit'
        required: false

env:
  PROJECT_FILE_PATH: ExplorerPatcher\ExplorerPatcher.vcxproj
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x64

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2025-vs2026
    timeout-minutes: 30
    steps:
      - name: Print inputs
        shell: bash
        run: |
          echo "ref: ${GITHUB_EVENT_INPUTS_REF}"
        env:
          GITHUB_EVENT_INPUTS_REF: ${{ github.event.inputs.ref }}

      - name: Checkout latest build and submodules
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        if: github.event.inputs.ref == ''
        with:
          submodules: recursive
          persist-credentials: false

      - name: Checkout specific build and submodules
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        if: github.event.inputs.ref != ''
        with:
          ref: ${{ github.event.inputs.ref }}
          submodules: recursive
          persist-credentials: false

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0

      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Enable SimpleWindowSwitcher support for newer Windows SDKs
        shell: cmd
        run: |
          cd libs/sws
          C:\msys64\usr\bin\wget.exe https://github.com/valinet/sws/commit/972acb76d1e6429133c92ed7cdefd29b9a2c6179.patch
          C:\msys64\usr\bin\dos2unix.exe 972acb76d1e6429133c92ed7cdefd29b9a2c6179.patch
          C:\msys64\usr\bin\dos2unix.exe SimpleWindowSwitcher/sws_def.h
          C:\msys64\usr\bin\patch.exe -N SimpleWindowSwitcher/sws_def.h 972acb76d1e6429133c92ed7cdefd29b9a2c6179.patch
          C:\msys64\usr\bin\unix2dos.exe SimpleWindowSwitcher/sws_def.h
          exit /b 0

      - name: Setup NuGet
        uses: nuget/setup-nuget@fd55a6f3b34392fa83fde1454582407d8c714123 # v4.0
        with:
          nuget-version: '7.x'

      - name: Restore NuGet packages
        run: |
          nuget restore ExplorerPatcher.sln

      - name: Build ExplorerPatcher (amd64)
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{env.BUILD_PLATFORM}} ${{env.PROJECT_FILE_PATH}}

      - name: Upload artifacts
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ExplorerPatcher.amd64_${{ steps.vars.outputs.sha_short }}_${{ github.ref_name }}
          path: |
            build/Release/x64/ExplorerPatcher.amd64.dll
          if-no-files-found: error
